<!--start footer-->
    <footer class="footer">
        <div class="container">
            <div class="row wow fadeInUp">
                <div class="col-sm-6 col-md-4 col-lg-4">
                    <div class="widget_title">
                        <h4><span>Contact Details</span></h4>
                    </div>
                    <div class="widget_content">
                        
                        <ul class="contact-details-alt">
                            <li><i class="fa fa-map-marker"></i> <p>
							Plot No. 25, Shivjyoti Colony,<br>
							Near Gajanan Canteen,<br> 
							Opp. MGM's Gate No. 5, N-6,<br>
							CIDCO, Nanded - 431005</p><br></li>
							<li><i class="fa fa-whatsapp"></i> <p>(+91) 9403821601</p></li>
                            <li><i class="fa fa-mobile"></i> <p>(+91) 9403821601</p></li>
                            <li><i class="fa fa-envelope-o"></i> <p><a href="#">kanadeaniket@sggs.ac.in </a></p></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-4">
                    <div class="widget_title">
                        <h4><span>Recent Posts</span></h4>
                    </div>
                    <div class="widget_content">
                      <ul class="links">
                        <li><a href="#">Latest Workshop.<span>September, 2017</span></a></li>
						<li><a href="#">Basic Workshop.<span>August 20, 2017</span></a></li>
                        <li><a href="#">Industrial Training Program <span>August 05, 2017</span></a></li>
                    </ul>
                    </div>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-4">
                    <div class="widget_title">
                        <h4><span>Twitter</span></h4>
                    </div>
                    <div class="widget_content">
                        <ul class="tweet_list">
                            <li class="tweet_content item">
                                <p class="tweet_link">aniket007</p>
                                <span class="time"></span>
                            </li>
                        </ul>
                    </div>
                    <div class="widget_content">
                        <div class="tweet_go"></div>
                    </div>
                </div>
                
            </div>
        </div>
    </footer>
	<!--end footer-->
	
	<section class="footer_bottom">
		<div class="container">
			<div class="row">
            <div class="col-sm-6">
                <p class="copyright">&copy; Copyright 2017 </p>
            </div>

            <div class="col-sm-6 ">
                <div class="footer_social">
                    <ul class="footbot_social">
                        <li><a class="fb" href="#." data-placement="top" data-toggle="tooltip" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                        <li><a class="twtr" href="#." data-placement="top" data-toggle="tooltip" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                        <li><a class="dribbble" href="#." data-placement="top" data-toggle="tooltip" title="Dribbble"><i class="fa fa-dribbble"></i></a></li>
                        <li><a class="skype" href="#." data-placement="top" data-toggle="tooltip" title="Skype"><i class="fa fa-skype"></i></a></li>
                        <li><a class="rss" href="#." data-placement="top" data-toggle="tooltip" title="RSS"><i class="fa fa-rss"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
		</div>
	</section>

    <script type="text/javascript" src="js/jquery-1.10.2.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.easing.1.3.js"></script>
    <script src="js/retina-1.1.0.min.js"></script>
    <script type="text/javascript" src="js/jquery.cookie.js"></script> <!-- jQuery cookie -->
    <!--<script type="text/javascript" src="js/styleswitch.js"></script> <!-- Style Colors Switcher -->
    <script type="text/javascript" src="js/jquery.fractionslider.js" charset="utf-8"></script>
    <script type="text/javascript" src="js/jquery.smartmenus.min.js"></script>
    <script type="text/javascript" src="js/jquery.smartmenus.bootstrap.min.js"></script>
    <script type="text/javascript" src="js/jquery.jcarousel.js"></script>
    <script type="text/javascript" src="js/jflickrfeed.js"></script>
    <script type="text/javascript" src="js/jquery.magnific-popup.min.js"></script>
    <script type="text/javascript" src="js/jquery.isotope.min.js"></script>
    <script type="text/javascript" src="js/swipe.js"></script>

    <script type="text/javascript" src="js/wow.min.js"></script>

    <script src="js/main.js"></script>

    <!-- Start Style Switcher 
    <div class="switcher"></div>-->
    <!-- End Style Switcher -->
    <script>
        $(window).load(function(){
            $('.slider').fractionSlider({
                'fullWidth': 			true,
                'controls': 			true,
                'responsive': 			true,
                'dimensions': 			"1200,400",
                'timeout' :             2000,
                'increase': 			true,
                'pauseOnHover': 		true,
                'slideEndAnimation': 	false,
                'autoChange':           true
            });
        });
        // WOW Animation
        new WOW().init();

       
    </script>
</body>
</html>
